name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Geração da snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Jonas-eng-21
          outputs: |
            ./github-contribution-grid-snake.svg
            ./github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit da snake animada
        uses: EndBug/add-and-commit@v9
        with:
          author_name: snake-bot
          author_email: actions@github.com
          message: "update snake animation"
